name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1-${{ github.run_number }}
          release_name: Automated build v0.1-${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf